name: Daily License Key Generator

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  generate_key:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate License Key
        id: generate_key
        run: |
          today=$(date +%Y%m%d)
          key=$(echo -n "KEY-$today-$RANDOM" | sha1sum | cut -c 1-16)
          echo "Generated License Key: $key"
          echo "::set-output name=license_key::$key"

      - name: Save License Key to File
        run: |
          echo "${{ steps.generate_key.outputs.license_key }}" > license_key.txt
          echo "License Key saved to file."

      - name: Commit and Push License Key
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add license_key.txt
          git commit -m "Daily License Key Update: ${{ steps.generate_key.outputs.license_key }}"
          git push
